[deps]
Adapt = "79e6a3ab-5dfb-504d-930d-738a2a938a0e"
GenericSparseArrays = "da3fe0eb-88a8-4d14-ae1a-857c283e9c70"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
JLArrays = "27aeb0d3-9eb9-45fb-866b-73c2ecf80fcb"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
